### ISSUE TITLE
可以出一个视频教程教一下如何配置环境如何设置使用吗

### ISSUE THREAD

**Issue by gakaks** [Abcuders/AutoAnimeMv#13]
### 请尽可能详细描述你的想法

RT 跟着教程走 也进行了配置 但是没有效果 不太清楚是Python没弄好还是设置有问题 方便出个视频介绍一下吗 感谢[https://pic7.58cdn.com.cn/nowater/webim/big/n_v22ad49d47e6d24df3bbf044d60389e4ae.png](url)附上设置图

**Comment by Abcuders** [comment]
> ### 请尽可能详细描述你的想法
> 
> RT 跟着教程走 也进行了配置 但是没有效果 不太清楚是Python没弄好还是设置有问题 方便出个视频介绍一下吗 感谢[https://pic7.58cdn.com.cn/nowater/webim/big/n_v22ad49d47e6d24df3bbf044d60389e4ae.png](url)附上设置图
> 
> ### 如可以，欢迎提供部分或全部实现上述功能的代码
> 
> _No response_

***

* 能否重新发下图，我都看不到你的图

**Comment by gakaks** [comment]
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v280d49449401640c18df1bb358dec2e93.png" alt="image.png" title="image.png" />](url)
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v289d3bbaa49a2407fa1221591090f0630.png" alt="image.png" title="image.png" />](url)
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v22d699ea775184e7faa7a1da53efba6aa.png" alt="image.png" title="image.png" />](url)
测试文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC][CHS_JP](0459DB1F)
测试文件名：[织梦字幕组][间谍教室 スパイ教室][07集][1080P][AVC][简日双语]
目前修改了盘符写法也没有生效 我是去Python官网安装了Python3 然后用命令装了requests(网络访问),zhconv(简繁互化)都显示下载完成 请问如何检测所需环境是否搭建完成

**Comment by Abcuders** [comment]
> [<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v280d49449401640c18df1bb358dec2e93.png" alt="image.png" title="image.png" />](url)
> [<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v289d3bbaa49a2407fa1221591090f0630.png" alt="image.png" title="image.png" />](url)
> [<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v22d699ea775184e7faa7a1da53efba6aa.png" alt="image.png" title="image.png" />](url)
> 测试文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC][CHS_JP](0459DB1F)
> 测试文件名：[织梦字幕组][间谍教室 スパイ教室][07集][1080P][AVC][简日双语]
> 目前修改了盘符写法也没有生效 我是去Python官网安装了Python3 然后用命令装了requests(网络访问),zhconv(简繁互化)都显示下载完成 请问如何检测所需环境是否搭建完成

***
* 你可以在命令行中手动执行这个工具(记得依次写上参数)，建议你每个参数都用“““包裹
> 工具路径也要用““包裹
```
Python3 “工具路径“ “参数1“ “参数2“
```
* 你遇到问题就是路径中存在空格，导致Python找不到工具

**Comment by gakaks** [comment]
> 
我按照命令符测试了一遍发现输入Python3会打开微软应用商店 我删除了3后程序可以运行了 也生成了log文件 但是文件里提示错误 手动输入也是错误 log文件：
[2023-06-26 10:15:06] INFO: Running....
[2023-06-26 10:15:06] INFO: 当前工具版本为2.2.0
[2023-06-26 10:15:06] INFO: 当前操作系统识别码为nt,posix/nt/java对应linux/windows/java虚拟机
[2023-06-26 10:15:06] INFO: 接受到的参数 > ['E:/anime/AutoAnimeMv-2.2.0/AutoAnimeMv.py', 'E:\\anime', '[织梦字幕组][间谍教室 スパイ教室][07集][1080P][AVC][简日双语].mp4', '1']
[2023-06-26 10:15:06] ERROR: 没有预料到的错误 > name 'LogsFileList' is not defined
[目前我的设置是这样：
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v28f89db2726ea4db3b9bd323bf54df74f.png" alt="image.png" title="image.png" />](url)

**Comment by Abcuders** [comment]
> > 
> 我按照命令符测试了一遍发现输入Python3会打开微软应用商店 我删除了3后程序可以运行了 也生成了log文件 但是文件里提示错误 手动输入也是错误 log文件：
> [2023-06-26 10:15:06] INFO: Running....
> [2023-06-26 10:15:06] INFO: 当前工具版本为2.2.0
> [2023-06-26 10:15:06] INFO: 当前操作系统识别码为nt,posix/nt/java对应linux/windows/java虚拟机
> [2023-06-26 10:15:06] INFO: 接受到的参数 > ['E:/anime/AutoAnimeMv-2.2.0/AutoAnimeMv.py', 'E:\\anime', '[织梦字幕组][间谍教室 スパイ教室][07集][1080P][AVC][简日双语].mp4', '1']
> [2023-06-26 10:15:06] ERROR: 没有预料到的错误 > name 'LogsFileList' is not defined
> [目前我的设置是这样：
> [<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v28f89db2726ea4db3b9bd323bf54df74f.png" alt="image.png" title="image.png" />](url)
> 
***
* 这是一个bug,原因是我忘了更新没有日志文件的相关逻辑,马上会push上的
* 临时解决办法,你可以在目标目录下新建几个日志文件比如这个"23-6-23.log"
* 也可以试着关闭日志定时清理功能,在配置文件中将RMLOGSFLAG设为False即可

**Comment by gakaks** [comment]
> 

[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v2c4edc4c0fb224c56afb9d61a8bb5ccf8.png" alt="image.png" title="image.png" />](url)
尝试了一下 好像还是不行 希望可以尽快更新

**Comment by Abcuders** [comment]
> > 
> 
> [![image.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url) 尝试了一下 好像还是不行 希望可以尽快更新

***
* 今天之内就更了，记得看

**Comment by gakaks** [comment]
> > > 
> > 
> > 
> > [![图片.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url)尝试一下希望还是不行希望可以尽快更新
> 
> * 今天之内就更了，记得看

谢谢大佬 给大佬点赞

**Comment by Abcuders** [comment]
> > > > 
> > > 
> > > 
> > > [![图片.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url)尝试一下希望还是不行希望可以尽快更新
> > 
> > 
> > 
> > * 今天之内就更了，记得看
> 
> 谢谢大佬 给大佬点赞

***
* 能来群里一下吗，有事

**Comment by gakaks** [comment]
> > > > > 
> > > > 
> > > > 
> > > > [![图片.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url)尝试了一下希望还是希望可以尽快更新
> > > 
> > > 
> > > 
> > > * 今天之内就更了，记得看
> > 
> > 
> > 谢谢大佬给大佬点赞
> 
> * 能来群里一下吗，内测，来测

只有电报群吗 有没有QQ群

**Comment by Abcuders** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > [![图片.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url)尝试了一下希望还是希望可以尽快更新
> > > > 
> > > > 
> > > > 
> > > > * 今天之内就更了，记得看
> > > 
> > > 
> > > 谢谢大佬给大佬点赞
> > 
> > 
> > 
> > * 能来群里一下吗，内测，来测
> 
> 只有电报群吗 有没有QQ群
***
* 没有，不方便我就发mail

**Comment by gakaks** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > [![图片.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url)尝试一下希望还是希望可以尽快更新
> > > > > 
> > > > > 
> > > > > 
> > > > > * 今天之内就更了，记得看
> > > > 
> > > > 
> > > > 谢谢大佬给大佬点赞
> > > 
> > > 
> > > 
> > > * 能来群里一下吗，内测，来测
> > 
> > 
> > 只有电报群吗 有没有QQ群
> 
> * 没有，不方便我就发mail

好吧 我试下 很久没上过电报了 不知道能不能登得上 国内手机号验证啥的

**Comment by gakaks** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > [![图片.png](https://camo.githubusercontent.com/e06979ce2ccc07ff7aa057434023f7d6955fee52600c41af3304e7d883271fba/68747470733a2f2f706963372e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763263346564633463306662323234633536616662396436316138626235636366382e706e67)](url)尝试一下希望还是希望可以尽快更新
> > > > > 
> > > > > 
> > > > > 
> > > > > * 今天之内就更了，记得看
> > > > 
> > > > 
> > > > 谢谢大佬给大佬点赞
> > > 
> > > 
> > > 
> > > * 能来群里一下吗，内测，来测
> > 
> > 
> > 只有电报群吗 有没有QQ群
> 
> * 没有，不方便我就发mail

果然上不去 一直在转 邮件吧 1047778281@qq.com

**Comment by Abcuders** [comment]
@gakaks ***
* 注意查收

**Comment by gakaks** [comment]
> @gakaks***
> 
> * 注意查收

测试成功了 间谍教室成功全自动完成结构重命名谢谢大佬 
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v20d6c3ac3ee1a48e395a01d2fb7673841.png" alt="image.png" title="image.png" />](url)
不过柯南识别出来很奇怪文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC][CHS_JP](0459DB1F).mp4
识别出来是OVA的一集：名侦探柯南 柯南、基德与水晶之母
我看是API返回的结果 有办法调整嘛
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v2bfe98383b84948eab1b70c35a62faebb.png" alt="image.png" title="image.png" />](url)

**Comment by Abcuders** [comment]
> > @gakaks***
> > 
> > * 注意查收
> 
> 测试成功了 间谍教室成功全自动完成结构重命名谢谢大佬 
> [<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v20d6c3ac3ee1a48e395a01d2fb7673841.png" alt="image.png" title="image.png" />](url)
> 不过柯南识别出来很奇怪文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC][CHS_JP](0459DB1F).mp4
> 识别出来是OVA的一集：名侦探柯南 柯南、基德与水晶之母
> 我看是API返回的结果 有办法调整嘛
> [<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v2bfe98383b84948eab1b70c35a62faebb.png" alt="image.png" title="image.png" />](url)

***
* Bgm API 的问题,在开发完TMDB API 之后可能可以解决
* 有个偏方,你可以禁用api 功能

**Comment by gakaks** [comment]
请问该如何禁用api功能
&nbsp;


一生为了爱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月26日(星期一) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Abcuders/AutoAnimeMv] 可以出一个视频教程教一下如何配置环境如何设置使用吗 (Issue #13)





   
@gakaks***
  
注意查收
   
测试成功了 间谍教室成功全自动完成结构重命名谢谢大佬
 
 不过柯南识别出来很奇怪文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC]CHS_JP.mp4
 识别出来是OVA的一集：名侦探柯南 柯南、基德与水晶之母
 我看是API返回的结果 有办法调整嘛
 
  
  
Bgm API 的问题,在开发完TMDB API 之后可能可以解决
 
有个偏方,你可以禁用api 功能

**Comment by gakaks** [comment]
> > 询问是否取消api功能
> >  
> > 一生为了爱
> > _**@**_ .***
> >  
> > ------------------ 原始邮件 ------------------
> > 发件人: _**@**_ . _**>;
> > 发送时间：2023年6月26日（周一）下午4:50
> > 食谱：_**@**_ . **_>;
> > 抄送：_**@**_ . _**>; _**@**_。**_>;
> > 主题：回复：[Abcuders/AutoAnimeMv] 可以出一个视频教程教一下如何配置环境如何设置使用吗（问题[＃13](https://github.com/Abcuders/AutoAnimeMv/issues/13)）
> > @gakaks***
> > 注意查收
> > 完成测试了间谍教室成功重新构造命名谢谢大佬
> > 柯南识别出来很奇怪文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC]CHS_JP.mp4识别出来是OVA
> > 的一集：名侦探柯南柯南、基德与水晶之母
> > 我看的是API返回的结果有办法调整好
> > Bgm API 的问题，在开发完成 TMDB API 之后可能可以解决
> > 存在偏方，你可以取消api功能
> > —
> > 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
> > 您收到此消息是因为您被提及。消息 ID：_**@**_ .***>
> 
> * 自己修改代码，或者使用1.0版本的代码(这个可以切换API功能)
> * 或者再等我更新

OK 那我等大佬更新吧 再次感谢

**Comment by Abcuders** [comment]
> > > 询问是否取消api功能
> > >  
> > > 一生为了爱
> > > _**@**_ .***
> > >  
> > > ------------------ 原始邮件 ------------------
> > > 发件人: _**@**_ . _**>;
> > > 发送时间：2023年6月26日（周一）下午4:50
> > > 食谱：_**@**_ . **_>;
> > > 抄送：_**@**_ . _**>; _**@**_。**_>;
> > > 主题：回复：[Abcuders/AutoAnimeMv] 可以出一个视频教程教一下如何配置环境如何设置使用吗（问题[＃13](https://github.com/Abcuders/AutoAnimeMv/issues/13)）
> > > @gakaks***
> > > 注意查收
> > > 完成测试了间谍教室成功重新构造命名谢谢大佬
> > > 柯南识别出来很奇怪文件名：[SBSUB][CONAN][1088][1080P][AVC_AAC]CHS_JP.mp4识别出来是OVA
> > > 的一集：名侦探柯南柯南、基德与水晶之母
> > > 我看的是API返回的结果有办法调整好
> > > Bgm API 的问题，在开发完成 TMDB API 之后可能可以解决
> > > 存在偏方，你可以取消api功能
> > > —
> > > 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
> > > 您收到此消息是因为您被提及。消息 ID：_**@**_ .***>
> > 
> > 
> > 
> > * 自己修改代码，或者使用1.0版本的代码(这个可以切换API功能)
> > * 或者再等我更新
> 
> OK 那我等大佬更新吧 再次感谢

***
* 看一下mail

**Comment by gakaks** [comment]
> > > > 询问是否取消api功能
> > > >  
> > > > 一生为了爱
> > > > _**@**_ .*** 
> > > >  
> > > > ------------------ 原始邮件 ----------------- -
> > > > 发件人：_**@**_。_**>;
> > > > 发送时间：2023年6月26日（周一）下午4:50
> > > > 食谱：_**@_** . **_>;
> > > > 抄送：_** @_ **. _** >；_**@**_。**_>;
> > > > 主题：回复：[Abcuders/AutoAnimeMv] 可以出一个视频教程一下如何配置环境如何设置使用吗（问题[＃13](https://github.com/Abcuders/AutoAnimeMv/issues/13)）
> > > > @gakaks***
> > > > 注意查收
> > > > 完成测试了间谍教室成功重新构造命名谢谢大佬
> > > > 柯南识别出来很奇怪文件名：[SBSUB][CONAN][1088][1 080P][AVC_AAC]CHS_JP.mp4识别出来是OVA的一集：
> > > > 名侦探柯南柯南、基德与水晶之母
> > > > 我看的是API返回的结果有一个调整好的
> > > > Bgm API的问题，在开发完成TMDB API之后可能可以解决
> > > > 如果存在偏方，您可以取消api功能
> > > > —
> > > > 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
> > > > 收到您此消息是因为您被提及。消息 ID：_**@**_ .***>
> > > 
> > > 
> > > 
> > > * 自己修改代码，或者使用1.0版本的代码(这个可以切换API功能)
> > > * 或者再等我更新
> > 
> > 
> > OK那我等大佬更新吧再次感谢
> 
> * 看一下邮件
[<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v2e245c4e648d644da9fefbcd9310a6ad9.png" alt="image.png" title="image.png" />](url)
禁用后直接CONAN了

**Comment by Abcuders** [comment]
> 

***
* 对就是这样，剩下的媒体库会自行处理的

**Comment by gakaks** [comment]
> > 
> 
> * 对就是这样，剩下的媒体库会自行处理的

好的我试试

**Comment by gakaks** [comment]
> > 
> 
> * 对就是这样，剩下的媒体库会自行处理的

测试后可以了 直接CONAN媒体库是刮不准的 会刮到一个电视节目:柯南季 手动识别一次之后就没有问题了 这个是因为资源的命名不够精准 但是手动识别之后 以后更新自动下载到这里是不用重新手动识别的
测试了一下孤独摇滚自动识别出来是Bocchi-the-Rock 这个命名很完整 可以自动被emby精准被刮削入库 全自动
基本上是解放双手了 如果有不准确的手动在媒体库识别一次即可 
太强了 谢谢大佬的分享和帮助

**Comment by Abcuders** [comment]
***
* 以后估计就不用手动了(现在有一些特典各方API数据不一样什么剧季什么剧季什么的也要手动)，更新其他的API应该会缓解，如果你有什么建议请直接告诉我

gakaks ***@***.***> 于 2023年6月26日周一 22:19写道：
