### ISSUE TITLE
[无法实现] 能否实现对完全未命名集数的动画进行命名

### ISSUE THREAD

**Issue by sayou112** [Abcuders/AutoAnimeMv#17]
### 请尽可能详细描述你的想法

大致思路是用FFmpeg隔3秒截一张图，输出集数，这个方法要求动画标题本身就有集数，没有的的就没办法

### 如可以，欢迎提供部分或全部实现上述功能的代码

```python
import os
import re
import subprocess

# 获取视频文件
videos = os.sys.argv[1:]

# 对每个视频文件执行以下操作
for video in videos:
    # 获取视频文件名
    video_name = os.path.basename(video)

    # 从文件名中截取“第 ”和“ 话”中间的两位数字
    if re.search("第(\d{2})話", video_name):
        episode = re.search("第(\d{2})話", video_name).group(1)
    else:
        raise Exception("无法从文件名中获取集数")
        continue

    # 使用ffmpeg对视频隔3秒截图，输出文件名格式为集数_四位数字.png
    cmd = f'ffmpeg -i "{video}" -vf "fps=1/3,scale=910:512" -ss 2:10 -to 00:21:00 "F:\\cocotemp1\\new4\\{episode}_%04d.png"'
    subprocess.run(cmd, shell=True)
```

**Comment by sayou112** [comment]
另一个的思路，不知道能不能用
先用FFmpeg截图发现标题，再安装配合日文OCR库，OCR出标题，再链接对应的wiki，找到标题集数那个表格，进行比对，因为OCR有错误率，所以60%匹配即为匹配成功，成功后对视频文件进行重命名，一般是集数和标题，以上需要视频处理，图片处理，OCR和爬虫，感觉比较复杂，

用gpt写了下，感觉不能直接用
1. 请确保已经安装了必要的库，例如os, subprocess, opencv-python (cv2), pytesseract, wikipedia-api 和 bs4
2. .2. 如前面所说，ffmpeg应该被正确安装和配置。
3. Pytesseract只是一个python接口用于与已安装的Tesseract OCR引擎通信。你需要在你的机器上安装Tesseract并添加它到你的系统路径中。
 4. 为了支持日语OCR，你需要安装对应的训练数据。
 5. Wikipedia API也需要额外的安装和设置。
 6.你需要使用 BeautifulSoup（一个Python库）来解析维基百科页面并提取表格数据。
--
````python
# 获取维基百科页面内容并解析标题
wiki_html = Wikipedia('ja').page(wiki_url).html()
soup = BeautifulSoup(wiki_html, 'html.parser')

# 找到'各話リスト'对应的表格
wiki_table = None
for header in soup.find_all(['h2', 'h3']):
    if '各話リスト' in header.text:
        sibling = header.find_next_sibling()
        while sibling and wiki_table is None:
            if sibling.name == 'table':
                wiki_table = sibling
            sibling = sibling.find_next_sibling()

# 提取表格中的集数和标题
wiki_episodes = []
if wiki_table is not None:
    for row in wiki_table.tbody.find_all('tr')[1:]:  # Skip the table header
        columns = row.find_all('td')
        episode = columns[0].get_text().strip()
        title = columns[1].get_text().strip()
        wiki_episodes.append((episode, title))
```

然后，在每个视频文件循环中，你可以将OCR文本与这些维基百科标题进行匹配：

```python
# 将OCR文本与维基百科标题进行匹配
matched_title = next((title for ep, title in wiki_episodes if ep == episode and title in ocr_text), None)

if matched_title is not None:
    # 如果找到匹配，将视频文件重命名
    new_video_name = f'{episode}_{matched_title}{os.path.splitext(video)[1]}'
    os.rename(video, os.path.join(video_dir, new_video_name))
else:
    print(f'无法匹配视频的名字: {video_name}')
````

**Comment by Abcuders** [comment]
话说，没有标剧集的种子是不是太逆天了，你有发现案例吗

**Comment by sayou112** [comment]
不是种子，是压制完成后需要一个一个用vlc对应着重命名剧集，尤其是那些排序很乱的m2ts，命名完再制种，年番这些比较麻烦

**Comment by Abcuders** [comment]
@sayou112 您是字幕组的吗

**Comment by sayou112** [comment]
是，感谢
麻烦了，可能比较复杂
源代码是powershell的，不过只能执行一个，还是希望能批量一个文件夹的
# 获取拖放的视频文件
$videos = $args

<# # 检查ffmpeg是否存在，如果不存在则下载
if (-not (Test-Path "ffmpeg.exe")) {
    Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip" -OutFile "ffmpeg.zip"
    Expand-Archive -Path "ffmpeg.zip" -DestinationPath ".\"
    Rename-Item -Path ".\ffmpeg-release-essentials\bin\ffmpeg.exe" -NewName "ffmpeg.exe"
    Remove-Item -Path ".\ffmpeg-release-essentials" -Recurse
    Remove-Item -Path ".\ffmpeg.zip"
}
 #>
 
# 对每个视频文件执行以下操作
foreach ($video in $videos) {
    # 获取视频文件名
    $videoName = Split-Path -Path $video -Leaf

    # 从文件名中截取“第”和“话”中间的两位数字
    if ($videoName -match "第(\d{2})話") {
        $episode = $Matches[1]
    }
    else {
        Write-Error "无法从文件名中获取集数"
        continue
    }

    # 使用ffmpeg对视频隔3秒截图，输出文件名格式为集数_四位数字.png
    & ffmpeg.exe -i $video -vf "fps=1/3,scale=910:512" -ss 2:10 -to 00:21:00 `"F:\cocotemp1\new4\"$episode"_%04d.png`"
}

**Comment by Abcuders** [comment]
@sayou112 方便进群吗，我看看今天能不能更，做好了好内测

**Comment by sayou112** [comment]
tg吗？下班看下

**Comment by Abcuders** [comment]
@sayou112 是，麻烦了
