### ISSUE TITLE
关于做种

### ISSUE THREAD

**Issue by KElee01** [Abcuders/AutoAnimeMv#29]
### 请尽可能详细描述你的想法

感谢你们的工作！现在 Infuse 识别元数据终于没那么麻烦了。
但是我想知道能不能在改名的之后也继续保证文件做种上传？比如添加一个配置项，允许在改名之前把原文件复制一份到其他路径里（最好在下载文件夹的外部，这样不会搞乱资料库），不知道能不能加上这个功能？

**Comment by Abcuders** [comment]
有这个功能，开启硬link就可以了
