### ISSUE TITLE
字幕语言识别异常

### ISSUE THREAD

**Issue by Qs315490** [Abcuders/AutoAnimeMv#34]
### 所用版本&操作系统

2.(11.5).0

### 遇到的问题

[Snow-Raws] 学園黙示録 HIGHSCHOOL OF THE DEAD 第01話 (BD 1920x1080 HEVC-YUV420P10 FLAC).tc.ass
识别为简体中文，因为 `HIGHSCHOOL` 中存在字符 `SC`

### 运行日志

.

**Comment by Abcuders** [comment]
知道了

**Comment by Abcuders** [comment]
已修复
