### ISSUE TITLE
识别集数异常

### ISSUE THREAD

**Issue by LCX149** [Abcuders/AutoAnimeMv#35]
### 所用版本&操作系统

2.(11.5).0；alpine

### 遇到的问题

第8集总是错误识别成179，其他集数正常。

### 运行日志

<img width="771" alt="无标题" src="https://github.com/Abcuders/AutoAnimeMv/assets/75821835/1d2f63e1-8b46-4a06-9074-6f952162f1da">

**Comment by Abcuders** [comment]
了解了

**Comment by Abcuders** [comment]
已修复
