### ISSUE TITLE
关于rss或者番剧站的网址

### ISSUE THREAD

**Issue by chococatlate1** [Abcuders/AutoAnimeMv#4]
能留个rss或者番剧站的网址吗

**Comment by lijiusong** [comment]
有个问题，如果标题中已经含有S01E01这类的规则命名，他就不会去归类处理，这怎么办

**Comment by Abcuders** [comment]
> 有个问题，如果标题中已经含有S01E01这类的规则命名，他就不会去归类处理，这怎么办

我会在下一个版本优化这个判断的，你现在可以把341行的code

```
if search(r'S\d{1,2}E\d{1,4}',File,flags=I) == None:
```
改成
```
if None = None:
```
来关闭这个功能
