### ISSUE TITLE
[Feature]请求TMDB时请求没有添加API-Key（个人申请）

### ISSUE THREAD

**Issue by SantaSati** [Abcuders/AutoAnimeMv#40]
### 请尽可能详细描述你的想法

请求没有附加TMDB的api会导致无效返回
```json
{
    "status_code": 7,
    "status_message": "Invalid API key: You must be granted a valid key.",
    "success": false
}
```

https://github.com/AutoAnimeMV-Teams/AutoAnimeMv/blob/2e4afa689ee115bf9b289e8126247b064de59a1d/AutoAnimeMv.py#L521-L525

### 如可以，欢迎提供部分或全部实现上述功能的代码

请求链接修改为 `f"https://api.themoviedb.org/3/search/tv?api_key={TMDB_API}&..." `，且需要添加一个全局变量`TMDB_API`

**Comment by Abcuders** [comment]
AAM工具使用Authorization来进行鉴权，不需要APIkey

* 见468行code
![Screenshot_20240403-063557_GitHub.png](https://github.com/AutoAnimeMV-Teams/AutoAnimeMv/assets/125891113/e7a30267-4ab1-4849-82f0-d21c16924e4b)

* 请问你是遇到了什么困难了吗
