### ISSUE TITLE
[Bug] 同#41

### ISSUE THREAD

**Issue by Liserng** [Abcuders/AutoAnimeMv#42]
### 所用版本&操作系统

群晖 7.1

### 遇到的问题

出现未预料到的问题，2.x版本能正常使用

配置文件：
[#Config]
PRINTLOGFLAG = True # 打印log开关
USEMODULE = False # 使用模块
NOTLOADEXTLIST = ''

# NetConfig
HTTPPROXY = 'http://192.168.31.245:7890' # Http代理
HTTPSPROXY = 'http://192.168.31.245:7890' # Https代理
ALLPROXY = '' # 全部代理
USEBGMAPI = True # 使用BgmApi
USETMDBAPI = True #使用TMDBApi

# File处理Config
USELINK = False # 使用硬链接开关
LINKFAILSUSEMOVEFLAGS = True #硬链接失败时使用MOVE
RMLOGSFLAG = '7' # 日志文件超时删除,填数字代表删除多久前的
MANDATORYCOVER = False # 强制覆盖文件

# FileName处理Config
JELLYFINFORMAT = False # jellyfin 使用 ISO/639 标准 简体和繁体都使用chi做标识
USETITLTOEP = False # 给每个番剧视频加上番剧Title 

# QBConfig
USERQBAPI = False # 使用QBApi
QBIP = '192.168.1.112' # QB的ip
QBPORT = 8081 # QBApi端口
QBUSERNAME = 'admin' # Qb账号
QBPASSWORD = 'Syn123456!' # Qb密码

# 附加Config
TIMELAPSE = 0 # 延时处理番剧
SEEPSINGLECHARACTER =False # SE EP单字符模式

### 运行日志

[2024-04-18 09:16:29] INFO: 当前工具版本为3.1.2
[2024-04-18 09:16:29] INFO: 当前操作系统识别码为posix,posix/nt/java对应linux/windows/java虚拟机
[2024-04-18 09:16:29] INFO: filepath:None filename:None number:None categoryname:None
[2024-04-18 09:16:29] ERROR: 没有预料到的错误 > name 'ComKey' is not defined
Traceback (most recent call last):
  File "AutoAnimeMv.py", line 580, in <module>
    Auxiliary_WriteLog()
  File "AutoAnimeMv.py", line 292, in Auxiliary_WriteLog
    LogPath = filepath if 'filepath' in globals() and path.exists(filepath) == True else PyPath
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by Abcuders** [comment]
运行日志能再给全一点吗，你是怎样传参的

**Comment by Liserng** [comment]
我输的命令是这个
python3 AutoAnimeMv.py help
不过处理番剧文件好像可以正常使用

**Comment by Abcuders** [comment]
那就对了，因为help的功能没什么用，我打算重写，但忘记还没写完，不小心把没重写完的部分推上去了，过几天就改
