### ISSUE TITLE
[Enhancement] 批处理错误文件不阻断后续逻辑优化

### ISSUE THREAD

**Issue by AgentNo7** [Abcuders/AutoAnimeMv#43]
### 所用版本&操作系统

Windows 10

### 遇到的问题

废话在前：正打算美滋滋看番。发现番剧文件夹好久没变化了，每次都要手动找。一看发现前两天换了python环境变量，qb脚本没法跑通了。然后就用批处理来整，结果发现处理半天文件都不全。发现了中间遇到异常脚本就会中断的问题。寻思，不就py嘛，我应该也能改，就整了这个issue和pr。
看下面：
因为特别篇无法识别，导致整个目录后续的文件都无法继续归类。
遂改为跳过一切异常并warn而不是中断的方式。
修复前
![image](https://github.com/AutoAnimeMV-Teams/AutoAnimeMv/assets/30135292/49d4c4ab-2744-47da-8b16-ccfcd78b7581)
修复后
![image](https://github.com/AutoAnimeMV-Teams/AutoAnimeMv/assets/30135292/653553a2-29e0-4567-a4d8-debdc456efae)

### 运行日志

修复前
![image](https://github.com/AutoAnimeMV-Teams/AutoAnimeMv/assets/30135292/49d4c4ab-2744-47da-8b16-ccfcd78b7581)
修复后
![image](https://github.com/AutoAnimeMV-Teams/AutoAnimeMv/assets/30135292/653553a2-29e0-4567-a4d8-debdc456efae)

**Comment by Abcuders** [comment]
* 感谢感谢提issue，不过此类问题提enhancement标签比较合适
* 本地版本在更新,所以我取消了你的PR,下次有PR 请先提issue,得到支持后再PR ,我会马上更新相应的说明文档的
* 看我的屎山代码为难你了🥹
* 还有其他什么建议吗

**Comment by AgentNo7** [comment]
> * 感谢感谢提issue，不过此类问题提enhancement标签比较合适
> * 本地版本在更新,所以我取消了你的PR,下次有PR 请先提issue,得到支持后再PR ,我会马上更新相应的说明文档的
> * 看我的屎山代码为难你了🥹
> * 还有其他什么建议吗

发个dev版本的分支吧，平时有事没事push一下dev，文档里标注dev分支不稳定但是更得快。要是有dev分支我应该也就不用花时间改脚本了。

**Comment by Abcuders** [comment]
> > * 感谢感谢提issue，不过此类问题提enhancement标签比较合适
> > * 本地版本在更新,所以我取消了你的PR,下次有PR 请先提issue,得到支持后再PR ,我会马上更新相应的说明文档的
> > * 看我的屎山代码为难你了🥹
> > * 还有其他什么建议吗
> 
> 发个dev版本的分支吧，平时有事没事push一下dev，文档里标注dev分支不稳定但是更得快。要是有dev分支我应该也就不用花时间改脚本了。

谢谢，了解了
