### ISSUE TITLE
希望能开发一个批处理

### ISSUE THREAD

**Issue by xqingting** [Abcuders/AutoAnimeMv#5]
RT，rss固然很香，但硬盘里有一些比较老的文件希望也能处理，可以封装一下？实现，选中文件夹然后批处理所有文件

**Comment by xqingting** [comment]
用ChatGPT写了一个。https://github.com/xqingting/MultiAnimeMv

**Comment by Abcuders** [comment]
加上日程了

**Comment by xqingting** [comment]
> 加上日程了

其实还有一个功能，我是webdav用户，现在的flow是qbit下载后自动刮削然后手动上传到阿里云盘再在全平台观看。但其实阿里云盘有非常多资源，理论上不需要上传。
也许可以针对阿里云盘的资源做一个识别的优化，阿里云盘现在是这样的
![image](https://github.com/Abcuders/AutoAnimeMv/assets/30023378/b604870e-0b1b-4d3c-8a1f-a5962b0319d7)
或者就是什么关注01-关注公众号什么的。

**Comment by wzfdgh** [comment]
> > 加上日程了
> 
> 其实还有一个功能，我是webdav用户，现在的flow是qbit下载后自动刮削然后手动上传到阿里云盘再在全平台观看。但其实阿里云盘有非常多资源，理论上不需要上传。 也许可以针对阿里云盘的资源做一个识别的优化，阿里云盘现在是这样的 ![image](https://user-images.githubusercontent.com/30023378/243760068-b604870e-0b1b-4d3c-8a1f-a5962b0319d7.png) 或者就是什么关注01-关注公众号什么的。

脚本目前是配合qbit使用的 咱们会先把下载文件识别做完
云盘下载文件命名较杂 欢迎多多提供样本捏~

**Comment by Abcuders** [comment]
> > 加上日程了
> 
> 其实还有一个功能，我是webdav用户，现在的flow是qbit下载后自动刮削然后手动上传到阿里云盘再在全平台观看。但其实阿里云盘有非常多资源，理论上不需要上传。
> 也许可以针对阿里云盘的资源做一个识别的优化，阿里云盘现在是这样的
> ![image](https://github.com/Abcuders/AutoAnimeMv/assets/30023378/b604870e-0b1b-4d3c-8a1f-a5962b0319d7)
> 或者就是什么关注01-关注公众号什么的。
> 

多多提供样本捏

**Comment by xqingting** [comment]
> 加上日程了

用ChatGPT写了一个。https://github.com/xqingting/MultiAnimeMv

**Comment by Abcuders** [comment]
> > 加上日程了
> 
> 用ChatGPT写了一个。https://github.com/xqingting/MultiAnimeMv

看见了，给你点赞👍

**Comment by Abcuders** [comment]
> > > 加上日程了
> > 
> > 
> > 其实还有一个功能，我是webdav用户，现在的flow是qbit下载后自动刮削然后手动上传到阿里云盘再在全平台观看。但其实阿里云盘有非常多资源，理论上不需要上传。
> > 也许可以针对阿里云盘的资源做一个识别的优化，阿里云盘现在是这样的
> > ![image](https://user-images.githubusercontent.com/30023378/243760068-b604870e-0b1b-4d3c-8a1f-a5962b0319d7.png)
> > 或者就是什么关注01-关注公众号什么的。
> 
> 多多提供样本捏

能否提供一些样本

**Comment by Abcuders** [comment]
> RT，rss固然很香，但硬盘里有一些比较老的文件希望也能处理，可以封装一下？实现，选中文件夹然后批处理所有文件

已经加入了

**Comment by Abcuders** [comment]
问题`一些标题处理过后会出现惊人的每集一个文件夹` 这是因为同一个字幕组对同一个番剧的不同剧集命名混乱导致的,我下一个版本会进行处理的

**Comment by Abcuders** [comment]
> 问题`一些标题处理过后会出现惊人的每集一个文件夹` 这是因为同一个字幕组对同一个番剧的不同剧集命名混乱导致的,我下一个版本会进行处理的

> 更新了，来测
