### ISSUE TITLE
S03剧集识别引发崩溃等一系列问题

### ISSUE THREAD

**Issue by xqingting** [Abcuders/AutoAnimeMv#6]
例如 [Lilith-Raws] Kaguya-sama wa Kokurasetai S03 - 13 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4

**Comment by Abcuders** [comment]
> 例如 [Lilith-Raws] Kaguya-sama wa Kokurasetai S03 - 13 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4
>

能否具体说明一下

**Comment by wzfdgh** [comment]
> ![image](https://user-images.githubusercontent.com/30023378/243762401-1a8a3aa9-e253-4189-b422-2cfbb81f1714.png) liru例如这个就无法好好识别。 ![image](https://user-images.githubusercontent.com/30023378/243762513-ba0993ae-a97d-4ed0-aba9-c9c1cd0ab146.png) 文件夹是第一季，而且只有和S03相同的第三集成功进入

能否将full-log贴出来看看

**Comment by xqingting** [comment]
[2023-06-07.log](https://github.com/Abcuders/AutoAnimeMv/files/11666998/2023-06-07.log)

**Comment by xqingting** [comment]
又出现了一个很相似的错误。
![image](https://github.com/Abcuders/AutoAnimeMv/assets/30023378/8cfcfbc5-dd4e-4704-ae32-94f3ff9de547)
赛马娘2，这个命名规则[LoliHouse] Uma Musume Pretty Derby Season 2 - 12 [BDRip 1080p HEVC-10bit FLACx2]最后识别出来的是
![image](https://github.com/Abcuders/AutoAnimeMv/assets/30023378/77bae366-6c1b-4044-8481-ab7157810a32)
一个是Season2没识别出来，另一个是仅仅有第二集

**Comment by xqingting** [comment]
还遇到了一个很好玩的...就是番剧名很少见的数字的86 不存在的战区，被识别成了s01e86

**Comment by wzfdgh** [comment]
> 还遇到了一个很好玩的...就是番剧名很少见的数字的86 不存在的战区，被识别成了s01e86

感谢反馈~

**Comment by Abcuders** [comment]
@xqingting 这个是因为我没给剧集识别做倒序识别

**Comment by Abcuders** [comment]
#6 的全部问题已经修复了(除了多File的那个)

**Comment by Abcuders** [comment]
> ![图像](https://user-images.githubusercontent.com/30023378/243767511-badf9365-eec4-454d-bc42-43dcf55614e1.png) 这种v2也不支持的，多次遇到了 [2023-06-07 00:42:18] ERROR: 未配出剧集，请检查(程序目标前不支持特典和电影)...EXIT

能否提供更多log，我认为这个是合集的问题，我们应该还没有做 ，v2识别应该没有问题

**Comment by xqingting** [comment]
> 

在使用你刚刚更新的代码以后，现在能正常识别了。我把两个log都放进来
[2023-06-10.log](https://github.com/Abcuders/AutoAnimeMv/files/11708190/2023-06-10.log)
[2023-06-09.log](https://github.com/Abcuders/AutoAnimeMv/files/11708191/2023-06-09.log)

**Comment by Abcuders** [comment]
> > 
> 
> 在使用你刚刚更新的代码以后，现在能正常识别了。我把两个log都放进来
> [2023-06-10.log](https://github.com/Abcuders/AutoAnimeMv/files/11708190/2023-06-10.log)
> [2023-06-09.log](https://github.com/Abcuders/AutoAnimeMv/files/11708191/2023-06-09.log)

那就好，再有什么bug欢迎反馈

**Comment by xqingting** [comment]
> > > 
> > 
> > 
> > 在使用你刚刚更新的代码以后，现在能正常识别了。我把两个log都放进来
> > [2023-06-10.log](https://github.com/Abcuders/AutoAnimeMv/files/11708190/2023-06-10.log)
> > [2023-06-09.log](https://github.com/Abcuders/AutoAnimeMv/files/11708191/2023-06-09.log)
> 
> 那就好，再有什么bug欢迎反馈

[2023-06-11 02:53:51] INFO: 当前工具版本为1.15.1
[2023-06-11 02:53:51] INFO: 当前操作系统识别码为nt,posix/nt/java对应linux/windows/java虚拟机
[2023-06-11 02:53:51] INFO: 接受到参数 ==> ['F:\\Downloads\\动漫\\AutoAnimeMv.py', 'update']
[2023-06-11 02:53:51] INFO: 准备更新中
[2023-06-11 02:53:53] ERROR: Get https://raw.githubusercontent.com/Abcuders/AutoAnimeMv/main/ 失败,未能获取到Update 内容,请检查您是否启用了系统代理,如是则您应该在此工具中配置代理信息
[2023-06-11 02:53:53] ERROR 未知的参数 ==> ['F:\\Downloads\\动漫\\AutoAnimeMv.py', 'update']
[2023-06-11 02:53:53] INFO: 现在是本地番剧文件批处理模式,正在扫描Path ==> update
Traceback (most recent call last):
  File "F:\Downloads\动漫\AutoAnimeMv.py", line 302, in <module>
    SavePath,VideoName,AssList,CategoryName = GetArgv()
  File "F:\Downloads\动漫\AutoAnimeMv.py", line 144, in GetArgv
    FileList = listdir(SavePath)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'update'

**Comment by Abcuders** [comment]
> 



> > > > 
> > > 
> > > 
> > > 在使用你刚刚更新的代码以后，现在能正常识别了。我把两个log都放进来
> > > [2023-06-10.log](https://github.com/Abcuders/AutoAnimeMv/files/11708190/2023-06-10.log)
> > > [2023-06-09.log](https://github.com/Abcuders/AutoAnimeMv/files/11708191/2023-06-09.log)
> > 
> > 
> > 那就好，再有什么bug欢迎反馈
> 
> [2023-06-11 02:53:51] INFO: 当前工具版本为1.15.1 [2023-06-11 02:53:51] INFO: 当前操作系统识别码为nt,posix/nt/java对应linux/windows/java虚拟机 [2023-06-11 02:53:51] INFO: 接受到参数 ==> ['F:\Downloads\动漫\AutoAnimeMv.py', 'update'] [2023-06-11 02:53:51] INFO: 准备更新中 [2023-06-11 02:53:53] ERROR: Get https://raw.githubusercontent.com/Abcuders/AutoAnimeMv/main/ 失败,未能获取到Update 内容,请检查您是否启用了系统代理,如是则您应该在此工具中配置代理信息 [2023-06-11 02:53:53] ERROR 未知的参数 ==> ['F:\Downloads\动漫\AutoAnimeMv.py', 'update'] [2023-06-11 02:53:53] INFO: 现在是本地番剧文件批处理模式,正在扫描Path ==> update Traceback (most recent call last): File "F:\Downloads\动漫\AutoAnimeMv.py", line 302, in SavePath,VideoName,AssList,CategoryName = GetArgv() File "F:\Downloads\动漫\AutoAnimeMv.py", line 144, in GetArgv FileList = listdir(SavePath) FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'update'

如log所示，,请检查您是否启用了系统代理,如是则您应该在此工具中配置代理信息,下面的Log是因为Python的exit()好像没有正常让工具退出，不过有bug或者提什么东西请去新提一个issues
```
[2023-06-11 02:53:53] ERROR 未知的参数 ==> ['F:\Downloads\动漫\AutoAnimeMv.py', 'update']
[2023-06-11 02:53:53] INFO: 现在是本地番剧文件批处理模式,正在扫描Path ==> update
Traceback (most recent call last):
File "F:\Downloads\动漫\AutoAnimeMv.py", line 302, in
SavePath,VideoName,AssList,CategoryName = GetArgv()
File "F:\Downloads\动漫\AutoAnimeMv.py", line 144, in GetArgv
FileList = listdir(SavePath)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'update'
```

**Comment by Abcuders** [comment]
> > 
> 
> > > > > 
> > > > 
> > > > 
> > > > 在使用你刚刚更新的代码以后，现在能正常识别了。我把两个log都放进来
> > > > [2023-06-10.log](https://github.com/Abcuders/AutoAnimeMv/files/11708190/2023-06-10.log)
> > > > [2023-06-09.log](https://github.com/Abcuders/AutoAnimeMv/files/11708191/2023-06-09.log)
> > > 
> > > 
> > > 那就好，再有什么bug欢迎反馈
> > 
> > 
> > [2023-06-11 02:53:51] INFO: 当前工具版本为1.15.1 [2023-06-11 02:53:51] INFO: 当前操作系统识别码为nt,posix/nt/java对应linux/windows/java虚拟机 [2023-06-11 02:53:51] INFO: 接受到参数 ==> ['F:\Downloads\动漫\AutoAnimeMv.py', 'update'] [2023-06-11 02:53:51] INFO: 准备更新中 [2023-06-11 02:53:53] ERROR: Get https://raw.githubusercontent.com/Abcuders/AutoAnimeMv/main/ 失败,未能获取到Update 内容,请检查您是否启用了系统代理,如是则您应该在此工具中配置代理信息 [2023-06-11 02:53:53] ERROR 未知的参数 ==> ['F:\Downloads\动漫\AutoAnimeMv.py', 'update'] [2023-06-11 02:53:53] INFO: 现在是本地番剧文件批处理模式,正在扫描Path ==> update Traceback (most recent call last): File "F:\Downloads\动漫\AutoAnimeMv.py", line 302, in SavePath,VideoName,AssList,CategoryName = GetArgv() File "F:\Downloads\动漫\AutoAnimeMv.py", line 144, in GetArgv FileList = listdir(SavePath) FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'update'
> 
> 如log所示，,请检查您是否启用了系统代理,如是则您应该在此工具中配置代理信息,但是由于我的大意，我忘记添加`不启用代理`相关code，马上修正，下面的Log是因为Python的exit()好像没有正常让工具退出，不过有bug或者提什么东西请去新提一个issues
> 
> ```
> [2023-06-11 02:53:53] ERROR 未知的参数 ==> ['F:\Downloads\动漫\AutoAnimeMv.py', 'update']
> [2023-06-11 02:53:53] INFO: 现在是本地番剧文件批处理模式,正在扫描Path ==> update
> Traceback (most recent call last):
> File "F:\Downloads\动漫\AutoAnimeMv.py", line 302, in
> SavePath,VideoName,AssList,CategoryName = GetArgv()
> File "F:\Downloads\动漫\AutoAnimeMv.py", line 144, in GetArgv
> FileList = listdir(SavePath)
> FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'update'
> ```

更新了，来测
