### ISSUE TITLE
请问和AutoBangumi的主要差异是什么呢

### ISSUE THREAD

**Issue by shininome** [Abcuders/AutoAnimeMv#8]
因为最近感觉这种类型的项目增加很多

**Comment by wzfdgh** [comment]
![image](https://github.com/Abcuders/AutoAnimeMv/assets/93830081/9b50669b-c833-476c-b570-9faff96f2cc6)

来自开发者的回答（w？

**Comment by Abcuders** [comment]
@shininome 轻量化，部署方便，方便维护，易扩展

**Comment by Abcuders** [comment]
易扩展 ，比如ab有些不支持的功能我们有，想要什么自己可以轻松的加
* AB不支持的总集篇，我们这个已经做了
* AB不支持硬链接，这个我们也做了

> 我们主打的就是一个 轻量化，快速部署（非常快，不骗你），对于懒人和小白很友好，你可以理解为AB没有你需要的功能时或者是你觉得AB不便携时用的替代品

目前这个项目也比较新，有什么功能要求可以多多提，更新很快的
